apiVersion: v1
kind: Service
metadata:
  name: nginx-example-svc
  labels:
    app: nginx-example
spec:
  type: ClusterIP
  selector:
    app: nginx-example
  ports:
    - port: 80
      targetPort: 80
